// Words on the page. The picture has its own strings in core/i18n.js.

const WEEK = {
  zh: ['日', '一', '二', '三', '四', '五', '六'],
  en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
}

export const weekday = (lang, n) => WEEK[lang][n]

export const ui = {
  zh: {
    htmlLang: 'zh-Hant',
    hero: '把你們的 LINE 對話<br>織成一塊布',
    sub: '一天一列，一小時一格，兩個人各一種線色。檔案只在這個分頁裡讀取，不會上傳。',
    sample: '先看範例',
    import: '匯入 LINE 匯出檔',
    importHint: '選 .txt 檔，或把檔案拖到這裡',
    howExport: '怎麼從 LINE 匯出？',
    json: '載入彙整 JSON',
    sampleBadge: '範例資料，不是真人對話',
    rangeTitle: '期間',
    days: (n) => `${n} 天`,
    endsOn: '結束日',
    colorsTitle: '配色',
    namesTitle: '標題與名字',
    titleLabel: '標題',
    nameA: '橫線的名字',
    nameB: '直線的名字',
    swap: '對調',
    savePng: '存成圖片',
    saveSvg: '存成 SVG',
    prevDay: '前一天',
    nextDay: '後一天',
    scrub: '拖動梭子選日期',
    readout: (date, wd, a, b, nameA, nameB) => `${date}（${wd}）　${nameA} ${a} 則，${nameB} ${b} 則`,
    privacy: '沒有伺服器，沒有帳號，也不存任何資料。這個頁面的安全政策擋掉所有對外連線，存成檔案離線也能用。',
    scope: '只畫匯出檔裡有的紀錄，不一定是完整的聊天歷史。目前讀得懂繁體中文版 LINE 手機匯出的兩人對話。',
    source: '原始碼',
    loaded: ({ records, start, end, days, nameA, countA, nameB, countB }) =>
      `讀到 ${records.toLocaleString('en-US')} 則紀錄，${start} 至 ${end}，共 ${days} 天。橫線是「${nameA}」（${countA.toLocaleString('en-US')} 則），直線是「${nameB}」（${countB.toLocaleString('en-US')} 則）。名字只留在這個分頁，不會印在圖上。`,
    skipped: (n) => `有 ${n} 行無法判讀，沒有計入。`,
    line: (n, why) => `第 ${n} 行：${why}`,
    issue: {
      bad_date: '日期不存在',
      weekday_mismatch: '日期和星期對不上，這一天的紀錄先略過',
      bad_time: '時間不合理',
      bad_record: '欄位數不對',
      no_date_line: '前面找不到日期行',
      unsupported_date: '看起來是日期，但格式讀不了，這一天的紀錄先略過',
      unclosed_quote: '引號沒有關上，後面的內容到下一個日期行為止都沒有計入',
    },
    error: {
      not_line_export: '這看起來不是 LINE 匯出的文字檔，或是格式還不支援。',
      too_many_senders: (n) => `找到至少 ${n} 位發話者。目前只支援兩人對話。`,
      one_sender: '只找到一位發話者，需要兩個人的對話。',
      group_chat: '這是群組聊天的匯出檔。目前只支援兩人對話。',
      too_dense: '單一小時的紀錄多到不合理，檔案可能不是 LINE 匯出檔。',
      save_failed: '存檔失敗，請換一個標題或名字再試一次。',
      too_big: '檔案太大了，請選 50 MB 以內的檔案。',
      aggregate: (why) => `彙整檔格式不對：${why}`,
      unreadable: '讀不了這個檔案。',
    },
    saved: '已存成檔案',
    themeAuto: '跟隨系統',
    themeLight: '淺色',
    themeDark: '深色',
    langSwitch: 'EN',
  },
  en: {
    htmlLang: 'en',
    hero: 'Weave your LINE chat<br>into cloth',
    sub: 'One row a day, one cell an hour, one thread color each. The file is read in this tab and never uploaded.',
    sample: 'Try the sample',
    import: 'Import a LINE export',
    importHint: 'Pick the .txt file, or drop it here',
    howExport: 'How to export from LINE',
    json: 'Load aggregate JSON',
    sampleBadge: 'Sample data, not a real chat',
    rangeTitle: 'Range',
    days: (n) => `${n} days`,
    endsOn: 'Ends on',
    colorsTitle: 'Colors',
    namesTitle: 'Title and names',
    titleLabel: 'Title',
    nameA: 'Name for the rows',
    nameB: 'Name for the columns',
    swap: 'Swap',
    savePng: 'Save picture',
    saveSvg: 'Save SVG',
    prevDay: 'Previous day',
    nextDay: 'Next day',
    scrub: 'Drag the shuttle to pick a day',
    readout: (date, wd, a, b, nameA, nameB) => `${date} (${wd})  ${nameA} ${a}, ${nameB} ${b}`,
    privacy: 'No server, no account, nothing stored. The page security policy blocks every outgoing request, and you can save the page and use it offline.',
    scope: 'Only the records in the export file are drawn, which may not be the full chat history. It reads two-person chats exported from the Traditional Chinese LINE mobile app.',
    source: 'Source',
    loaded: ({ records, start, end, days, nameA, countA, nameB, countB }) =>
      `Read ${records.toLocaleString('en-US')} records from ${start} to ${end} (${days} days). Rows are "${nameA}" (${countA.toLocaleString('en-US')}), columns are "${nameB}" (${countB.toLocaleString('en-US')}). Names stay in this tab and are not printed on the picture.`,
    skipped: (n) => `${n} lines could not be read and were not counted.`,
    line: (n, why) => `Line ${n}: ${why}`,
    issue: {
      bad_date: 'the date does not exist',
      weekday_mismatch: 'the date and weekday disagree, so records under it were skipped',
      bad_time: 'the time is not valid',
      bad_record: 'the wrong number of fields',
      no_date_line: 'no date line before it',
      unsupported_date: 'it looks like a date but the layout is not supported, so records under it were skipped',
      unclosed_quote: 'a quote was never closed, so what followed up to the next date line was not counted',
    },
    error: {
      not_line_export: 'This does not look like a LINE chat export, or its layout is not supported yet.',
      too_many_senders: (n) => `Found at least ${n} senders. Only two-person chats are supported.`,
      one_sender: 'Found one sender. A two-person chat is needed.',
      group_chat: 'This is a group chat export. Only two-person chats are supported.',
      too_dense: 'One hour holds an impossible number of records, so this may not be a LINE export.',
      save_failed: 'Saving failed. Try a different title or name.',
      too_big: 'That file is too large. Pick one under 50 MB.',
      aggregate: (why) => `The aggregate file is not valid: ${why}`,
      unreadable: 'That file could not be read.',
    },
    saved: 'Saved',
    themeAuto: 'System',
    themeLight: 'Light',
    themeDark: 'Dark',
    langSwitch: '中文',
  },
}
